# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TilesXYZ
                                 A QGIS plugin
 TilesXYZ
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-04-29
        copyright            : (C) 2019 by Marcel Dancak
        email                : marcel.dancak@lutraconsulting.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Marcel Dancak'
__date__ = '2019-04-29'
__copyright__ = '(C) 2019 by Marcel Dancak'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TilesXYZ class from file TilesXYZ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tiles_xyz import TilesXYZPlugin
    return TilesXYZPlugin()
